SELECT year, month, (evEVCO2 + evGasCO2) AS evCO2
FROM
(
    -- calculate the co2 generated by ev mileage portion of hybrid
    SELECT year, month, days, SUM( {1} / (epatmpg * '0.090634441') * (elecCO2/elec)) AS evEVCO2
    FROM
    (
        SELECT houseid, personid, tdtrpnum, year, month, vehid, trpmiles
        FROM TravelDay
        WHERE trpmiles >= {1} AND vehid >= 1
    ) trips NATURAL JOIN
    (
        SELECT houseid, vehid, epatmpg
        FROM Vehicle
    ) vehs NATURAL JOIN DaysInMonth NATURAL JOIN
    (
        -- correlate with total CO2 generated by electricity in each month
        SELECT year, month, value AS elecCO2
        FROM ElectricityCO2
    ) eia2 NATURAL JOIN
    (
        -- correlate with total (net) elecricty generated in each month
        SELECT year, month, value AS elec
        FROM ElectricityCO2
    ) eia3 
    GROUP BY year, month, days
) perHouseholdEV NATURAL JOIN
(
    -- calculate the co2 generated by gas mileage portion of hybrid (in metric tons of CO2)
    SELECT year, month, days, SUM( (trpmiles - {1}) / (epatmpg * '8.887E-3')) AS EVGasCO2
    FROM
    (
        SELECT houseid, personid, tdtrpnum, year, month, vehid, trpmiles
        FROM TravelDay
        WHERE trpmiles >= {1} AND vehid >= 1
    ) trips NATURAL JOIN
    (
        SELECT houseid, vehid, epatmpg
        FROM Vehicle
    ) vehs NATURAL JOIN DaysInMonth
    GROUP BY year, month, days
) perHouseholdEVTemp
