SELECT year, month, (evEVCO2) AS evCO2
FROM
(
    -- calculate the co2 generated by ev mileage portion of hybrid
    SELECT year, month, days, SUM( trpmiles / (epatmpg * '0.090634441') * (elecCO2/elec)) AS evEVCO2
    FROM
    (
        SELECT houseid, personid, tdtrpnum, year, month, vehid, trpmiles
        FROM TravelDay
        WHERE trpmiles <= {1} AND vehid >= 1
    ) trips NATURAL JOIN
    (
        SELECT houseid, vehid, epatmpg
        FROM Vehicle
    ) vehs NATURAL JOIN DaysInMonth NATURAL JOIN
    (
        -- correlate with total CO2 generated by electricity in each month
        SELECT year, month, value AS elecCO2
        FROM ElectricityCO2
    ) eia2 NATURAL JOIN
    (
        -- correlate with total (net) elecricty generated in each month
        SELECT year, month, value AS elec
        FROM ElectricityCO2
    ) eia3 
    GROUP BY year, month, days
) perHouseholdEV 
